### GENERAL SETTINGS ###

# Site settings
title: Broadband Network & Multimedia Lab.
description: "Computer vision research & Light Field Photography."
analytics: UA-62493043-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "jin-lab.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections: 
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

  publications:
    output: true
    permalink: /publications/:title/
  questions:
